spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:9090
          predicates:
            - Path=/students/**
        - id: employee-service
          uri: http://localhost:9091
          predicates:
            - Path=/employees/**